[package]
name = "{{ project_name }}"
version = "0.1.0"
authors = ["Amy Keibler <amelia.keibler@gmail.com>"]
edition = "2021"
description = "{{ project_description }}"

{% if license == "mit-plus-apache-2" -%}
license = "MIT OR Apache-2.0"
{%- else -%}
license-file = "LICENSE"
{%- endif %}

[dependencies]


{% if add_bom -%}
[package.metadata.cyclonedx]
included_dependencies = "all"
format = "json"
{%- endif %}
