default:
  @just --list

# Run the CI tests locally
ci:
  @echo 'Run the test suite'
  cargo nextest run --profile ci

  @echo 'Check formatting'
  cargo fmt --check

  @echo 'Check Clippy'
  cargo clippy

  @echo 'Checking Nix'
  nixpkgs-fmt --check **.nix

# Format all nix files
nix-fmt:
  nixpkgs-fmt **.nix
    
